pipeline {
  agent any
  environment {
    RELEASE='0.0.1'
  }
  
  stages {
    stage('Build') {
      // agent any
      environment {
        LOG_LEVEL='INFO'
      }
      parallel {
        stage('linux-arm64') {
          agent any
          steps {
            echo "Building release ${RELEASE} for ${STAGE_NAME}"
          }
        }
        stage('linux-amd64') {
          steps {
            echo "Building release ${RELEASE} for ${STAGE_NAME}"
          }
        }
      }
    }
    stage('Test') {
      steps {
        echo "Testing release ${RELEASE}..."
      }
    }
    stage('Deploy') {
      input {
        message 'Deploy?'
        ok 'Do it!'
        parameters {
          string(name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD', description: 'Target deploy env')
        }
      }
      steps {
        echo "Deploying to ${RELEASE} to environment ${TARGET_ENVIRONMENT}"
      }
    }
  }

  post {
    always {
      echo 'Prints wether depoly or not'
    }
  }
}